version: "3.8"

services:
  blog:
    image: ghcr.io/mikewon98/blog:latest
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_STRAPI_API_URL: https://deserving-bouquet-d41dc59d47.strapiapp.com
    env_file:
      - .env
    ports:
      - "3000:3000"
